### ISSUE TITLE
feat : greeting bot for pr

### ISSUE THREAD

**Issue by TenzDelek** [TenzDelek/DearDiary#77]
<img width="913" alt="image" src="https://github.com/user-attachments/assets/e04221bd-320f-485e-a7f9-f44e76900e9b">

**Comment by Sourabh782** [comment]
@TenzDelek i m intrested on implementing it

**Comment by j-mahapatra** [comment]
@TenzDelek I have raised a PR to add the required action for thank you comment. Please take a look.

**Comment by Sourabh782** [comment]
@j-mahapatra bro it's assigned to me, why u working without having the issue assigned?

**Comment by Sourabh782** [comment]
@TenzDelek isn't it against rules?

**Comment by j-mahapatra** [comment]
@Sourabh782 The issue has been open since more than a day. For such a small feature, it should not take more than 10-15 minutes. I just assumed that you have dropped working on the issue. Also, there is no "rule" as such in contribution guides of this repository. Please forgive me if I have missed it somewhere. You are also assigned another issue, please work on that one. :)

**Comment by j-mahapatra** [comment]
@Sourabh782 I couldn't find any of the above rules on neither the repository's code of conduct nor GSSOC code of conduct. Again, if I have missed it somewhere, it is completely my bad. It would be great if you could share a link to the rules that you have mentioned if possible. I just raised a PR because this is a very simple change and shouldn't take too long to add and the issue was showing "yesterday" when I raised the PR. Could you please let this one go since I have already raised the PR with the required changes?

**Comment by Sourabh782** [comment]
Ok sure no worries, it's better not get work work waste 😊
